= OLED Library for Arduino =

This library enables an Arduino board to communicate with the 1.5 Inch OLED RGB. 
It simplifies the process for drawing shapes, lines, images, and text to the screen. 

Source WaveshaRE :https://www.waveshare.com/wiki/1.5inch_RGB_OLED_Module


Improved version from WaveShare / STM32 libraries

Created OLED_Driver Class

Solved color bugs

Added transarant Text


For more information about this library please visit us at
https://github.com/javos65/Arduino_OLED_driver

== License ==

Copyright (c) Arduino LLC. All right reserved.
Copyright (c) Waveshare team

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
